### ISSUE TITLE
Why opened map shows invalid point ?

### ISSUE THREAD

**Issue by sergeynilov** [iMuMz/Nova4FieldMap#2]
In Laravel 10 / nova 4.27 app I added "imumz/nova-4-field-map": "^1.0", and added in resource :
```

            Number::make(__('Latitude'), 'geo_lat')->min(-90)->max(90)->required()->step('any'),
            Number::make(__('Longitude'), 'geo_lon')->min(-180)->max(180)->required()->step('any'),

            Text::make('Products count', function () {
                return $this->resource->products()->count();
            })->textAlign('right')->readonly(),

            Nova4FieldMap::make('Map View')
                ->type('LatLon')
                ->point($this->latitude,$this->longitude)
                ->popup('popup')
                ->height('400px'),

```

my model has 'geo_lat' and 'geo_lon' fields and I suppose that is why point om map is invalid :

https://prnt.sc/EAGtPBFRxsST

a) How to set using my fields ?

b) How can I set default zoom ?

c) Do I really need as valid Google Maps API ? I would use Leaflet - it does not use any key...

**Comment by iMuMz** [comment]
@sergeynilov 

```
Nova4FieldMap::make('Map View')
->type('LatLon')
->point($this->geo_lat,$this->geo_lon)
->height('400px'),
```

**Comment by sergeynilov** [comment]
Thanks!

2) If there is way to set default zoom ?
3) Looks like Google Maps API is not nessary actually. At least for my code.

**Comment by iMuMz** [comment]
@sergeynilov 

2. No zoom method available. Will add with a future update.
3. Google is not required at all. Default is Leaflet.

**Comment by sergeynilov** [comment]
Thanks for your job!
